

def sort_detection_boxes(boxes, x_tolerance=5.0):
    """
    This function generated by Qwen-3-Max AI
    This function groups boxes with similar x coordinates into columns.
    
    Parameters:
    boxes (numpy.ndarray): 2D array with shape (N, 6) where each row contains
                          [x1, y1, x2, y2, conf, cls]
    x_tolerance (float): Maximum distance in x direction to consider boxes in same column
    
    Returns:
    numpy.ndarray: Sorted array with the same shape as input
    """
    
    import numpy as np
    
    if boxes.size == 0:
        return boxes
    
    # Sort by x1 first to make column grouping easier
    sorted_by_x = boxes[np.argsort(boxes[:, 0])]
    
    # Group into columns
    columns = []
    current_column = [sorted_by_x[0]]
    
    for i in range(1, len(sorted_by_x)):
        current_x = sorted_by_x[i, 0]
        column_x = current_column[0][0]  # x1 of first box in current column
        
        if abs(current_x - column_x) <= x_tolerance:
            # Same column
            current_column.append(sorted_by_x[i])
        else:
            # New column
            columns.append(np.array(current_column))
            current_column = [sorted_by_x[i]]
    
    # Don't forget the last column
    if current_column:
        columns.append(np.array(current_column))
    
    # Sort each column by y1 and concatenate
    sorted_boxes = []
    for column in columns:
        column_sorted = column[np.argsort(column[:, 1])]
        sorted_boxes.extend(column_sorted.tolist())
    
    return np.array(sorted_boxes)

# Example usage and testing
if __name__ == "__main__":
    # Create sample detection boxes that demonstrate the column-wise sorting
    boxes = np.array([
        [100, 80, 150, 130, 0.9, 1],   # Column 3
        [50, 120, 80, 170, 0.8, 0],    # Column 1, bottom
        [100, 30, 140, 80, 0.95, 1],   # Column 3, top
        [50, 50, 90, 90, 0.85, 0],     # Column 1, top
        [150, 100, 200, 150, 0.7, 2],  # Column 4
        [75, 90, 110, 140, 0.88, 1],   # Column 2
        [75, 40, 105, 90, 0.92, 1],    # Column 2, top
    ])
    
    print("Original boxes:")
    for i, box in enumerate(boxes):
        print(f"  {i}: x1={box[0]:.0f}, y1={box[1]:.0f}")
    
    print("\nMethod 2 (tolerance-based grouping, x_tolerance=10):")
    sorted_boxes2 = sort_detection_boxes(boxes, x_tolerance=10)
    for i, box in enumerate(sorted_boxes2):
        print(f"  {i}: x1={box[0]:.0f}, y1={box[1]:.0f}")
